version: '3.8'

services:
  zenith:
    build: ./zenith
    ports:
      - "8080:8080"
    networks:
      - netw
    environment:
      SPRING_PROFILES_ACTIVE: dev

networks:
  netw:
    driver: bridge